// Firmware publishing CLI. It manages the persistent Ed25519 signing identity and pushes
// signed builds to a running cloud, and it emits the raw public key as a C array to bake into
// a device. Together these are the developer side of on-device OTA:
//
//   keygen   <key-path>                                  create a signing key
//   pubkey-c <key-path>                                  print the public key as C for a device
//   publish  <key-path> <type> <version> <bin> [url]     sign a build and publish it
//
// The private key never leaves the developer's machine; the device trusts only the matching
// public key, and the cloud verifies every published build against it.

import { readFileSync, writeFileSync } from "node:fs";
import { FirmwareSigner, rawEd25519PublicKey } from "./signing.js";

function usage(): never {
  process.stderr.write(
    "usage:\n" +
      "  keygen   <key-path>\n" +
      "  pubkey-c <key-path>\n" +
      "  publish  <key-path> <deviceType> <version> <artifact-path> [cloud-url]\n",
  );
  process.exit(2);
}

function loadSigner(keyPath: string): FirmwareSigner {
  return FirmwareSigner.fromPrivateKeyPem(readFileSync(keyPath, "utf8"));
}

function keygen(keyPath: string): void {
  const signer = new FirmwareSigner();
  writeFileSync(keyPath, signer.privateKeyPem, { mode: 0o600 });
  process.stdout.write(`wrote signing key to ${keyPath}\n`);
  process.stdout.write(signer.publicKeyPem);
}

function pubkeyC(keyPath: string): void {
  const raw = rawEd25519PublicKey(loadSigner(keyPath).publicKeyPem);
  const bytes = [...raw].map((b) => `0x${b.toString(16).padStart(2, "0")}`);
  const rows: string[] = [];
  for (let i = 0; i < bytes.length; i += 8) {
    rows.push("    " + bytes.slice(i, i + 8).join(", ") + ",");
  }
  process.stdout.write(
    "// Ed25519 signing public key, generated by `chipwright-cloud publish pubkey-c`.\n" +
      `static const unsigned char CW_SIGNING_PUBLIC_KEY[32] = {\n${rows.join("\n")}\n};\n`,
  );
}

async function publish(
  keyPath: string,
  deviceType: string,
  version: string,
  artifactPath: string,
  url: string,
): Promise<void> {
  const signer = loadSigner(keyPath);
  const artifact = readFileSync(artifactPath);
  const build = signer.sign(deviceType, version, artifact);
  const response = await fetch(`${url}/firmware`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ build, artifactBase64: artifact.toString("base64") }),
  });
  const body = await response.text();
  if (!response.ok) {
    process.stderr.write(`publish failed (${response.status}): ${body}\n`);
    process.exit(1);
  }
  process.stdout.write(`published ${deviceType}@${version} (${artifact.length} bytes): ${body}\n`);
}

async function main(): Promise<void> {
  const [command, ...args] = process.argv.slice(2);
  switch (command) {
    case "keygen":
      if (args.length !== 1) usage();
      keygen(args[0] as string);
      return;
    case "pubkey-c":
      if (args.length !== 1) usage();
      pubkeyC(args[0] as string);
      return;
    case "publish":
      if (args.length < 4 || args.length > 5) usage();
      await publish(
        args[0] as string,
        args[1] as string,
        args[2] as string,
        args[3] as string,
        args[4] ?? "http://127.0.0.1:8080",
      );
      return;
    default:
      usage();
  }
}

main().catch((error: unknown) => {
  process.stderr.write(`${(error as Error).message}\n`);
  process.exit(1);
});
