// Generated by Chipwright from the device manifest. Do not edit by hand.
// Device: smart_thermostat (thermostat)
//
// Vendored here so the ESP-IDF project builds without a generation step. Regenerate with:
//   node core/device-engine/dist/cli.js compile examples/thermostat/device.yaml --out <dir>

#ifndef CHIPWRIGHT_SMART_THERMOSTAT_INTERFACE_H
#define CHIPWRIGHT_SMART_THERMOSTAT_INTERFACE_H

#include "chipwright/sdk.h"

// temperature_sensor sensor (celsius)
#define CW_TEMPERATURE_SENSOR_MIN (-20)
#define CW_TEMPERATURE_SENSOR_MAX (50)
cw_status_t cw_temperature_sensor_read(float *out_value);

// hvac actuator
typedef enum {
  CW_HVAC_MODE_HEATING,
  CW_HVAC_MODE_COOLING,
  CW_HVAC_MODE_OFF,
} cw_hvac_mode_t;
cw_status_t cw_hvac_set_mode(cw_hvac_mode_t mode);

#endif  // CHIPWRIGHT_SMART_THERMOSTAT_INTERFACE_H
