// Generated by OpenHome Studio from the device manifest. Do not edit by hand.
// Device: smart_thermostat (thermostat)
//
// Vendored here so the ESP-IDF project builds without a generation step. Regenerate with:
//   node core/device-engine/dist/cli.js compile examples/thermostat/device.yaml --out <dir>

#ifndef OPENHOME_SMART_THERMOSTAT_INTERFACE_H
#define OPENHOME_SMART_THERMOSTAT_INTERFACE_H

#include "openhome/sdk.h"

// temperature_sensor sensor (celsius)
#define OH_TEMPERATURE_SENSOR_MIN (-20)
#define OH_TEMPERATURE_SENSOR_MAX (50)
oh_status_t oh_temperature_sensor_read(float *out_value);

// hvac actuator
typedef enum {
  OH_HVAC_MODE_HEATING,
  OH_HVAC_MODE_COOLING,
  OH_HVAC_MODE_OFF,
} oh_hvac_mode_t;
oh_status_t oh_hvac_set_mode(oh_hvac_mode_t mode);

#endif  // OPENHOME_SMART_THERMOSTAT_INTERFACE_H
