// Emits a C header describing the device's capabilities. This is the seam between the
// declarative manifest and firmware: a developer implements these prototypes against
// the SDK rather than writing chip-specific code by hand.

import type { Capability, DeviceIR, SensorCapability, ActuatorCapability } from "../schema.js";
import type { GeneratedFile, Generator } from "./index.js";

function upper(value: string): string {
  return value.toUpperCase();
}

function guard(deviceName: string): string {
  return `OPENHOME_${upper(deviceName)}_INTERFACE_H`;
}

function sensorSection(deviceName: string, cap: SensorCapability): string {
  const prefix = `oh_${cap.key}`;
  const lines: string[] = [];
  const unit = cap.unit ?? "unitless";
  lines.push(`// ${cap.key} sensor (${unit})`);
  if (cap.range !== null) {
    lines.push(`#define ${upper(prefix)}_MIN (${cap.range.min})`);
    lines.push(`#define ${upper(prefix)}_MAX (${cap.range.max})`);
  }
  lines.push(`oh_status_t ${prefix}_read(float *out_value);`);
  return lines.join("\n");
}

function actuatorSection(cap: ActuatorCapability): string {
  const prefix = `oh_${cap.key}`;
  const enumName = `${prefix}_mode_t`;
  const enumMembers = cap.modes
    .map((mode) => `  ${upper(prefix)}_MODE_${upper(mode)},`)
    .join("\n");
  return [
    `// ${cap.key} actuator`,
    `typedef enum {`,
    enumMembers,
    `} ${enumName};`,
    `oh_status_t ${prefix}_set_mode(${enumName} mode);`,
  ].join("\n");
}

function capabilitySection(deviceName: string, cap: Capability): string {
  return cap.kind === "sensor" ? sensorSection(deviceName, cap) : actuatorSection(cap);
}

export const firmwareInterfaceGenerator: Generator = {
  name: "firmware-interface",
  generate(ir: DeviceIR): GeneratedFile[] {
    const name = ir.device.name;
    const sections = ir.capabilities.map((cap) => capabilitySection(name, cap));
    const header = [
      `// Generated by OpenHome Studio from the device manifest. Do not edit by hand.`,
      `// Device: ${name} (${ir.device.category})`,
      ``,
      `#ifndef ${guard(name)}`,
      `#define ${guard(name)}`,
      ``,
      `#include "openhome/sdk.h"`,
      ``,
      ...(sections.length > 0 ? [sections.join("\n\n"), ``] : []),
      `#endif  // ${guard(name)}`,
      ``,
    ].join("\n");

    return [{ path: `firmware/${name}_interface.h`, contents: header }];
  },
};
