// Emits a baseline acceptance suite from the manifest. Every declared sensor is read and
// checked against its declared range, and every actuator mode is exercised, so each
// capability is tested automatically. The suite targets the abstract device target, so it
// runs on the twin today and on hardware unchanged.

import type { ActuatorCapability, DeviceIR, SensorCapability } from "../schema.js";
import type { GeneratedFile, Generator } from "./index.js";

function sensors(ir: DeviceIR): SensorCapability[] {
  return ir.capabilities.filter((cap): cap is SensorCapability => cap.kind === "sensor");
}

function actuators(ir: DeviceIR): ActuatorCapability[] {
  return ir.capabilities.filter((cap): cap is ActuatorCapability => cap.kind === "actuator");
}

function floatLiteral(value: number): string {
  return Number.isInteger(value) ? `${value}.0f` : `${value}f`;
}

export const testStubGenerator: Generator = {
  name: "test-stub",
  generate(ir: DeviceIR): GeneratedFile[] {
    const lines: string[] = [
      "// Generated by OpenHome Studio from the device manifest. Do not edit by hand.",
      `// Baseline acceptance suite for ${ir.device.name}.`,
      "",
      '#include "openhome/test.h"',
      "",
      "void oh_generated_suite(oh_test_run_t *run, oh_test_target_t *target) {",
      "  OH_EXPECT(run, target->connect(target->ctx) == OH_OK);",
    ];

    for (const sensor of sensors(ir)) {
      lines.push("");
      lines.push(`  float ${sensor.key} = 0.0f;`);
      lines.push(
        `  OH_EXPECT(run, target->read_sensor(target->ctx, "${sensor.key}", &${sensor.key}) == OH_OK);`,
      );
      if (sensor.range !== null) {
        lines.push(
          `  OH_EXPECT(run, ${sensor.key} >= ${floatLiteral(sensor.range.min)} && ` +
            `${sensor.key} <= ${floatLiteral(sensor.range.max)});`,
        );
      }
    }

    for (const actuator of actuators(ir)) {
      lines.push("");
      actuator.modes.forEach((mode, index) => {
        lines.push(
          `  OH_EXPECT(run, target->set_mode(target->ctx, "${actuator.key}", ${index}) == OH_OK);  // ${mode}`,
        );
      });
    }

    lines.push("}", "");
    return [{ path: `tests/${ir.device.name}_generated.c`, contents: lines.join("\n") }];
  },
};
