// Firmware scaffolding for the IDE. Where generate() emits regenerable artifacts that must
// not be edited by hand, scaffold() emits a starter firmware module the developer owns and
// edits: it implements the generated capability prototypes by delegating to the HAL, registers
// a driver for each capability, and runs the SDK telemetry loop. This closes the gap between a
// device definition and running code without asking the developer to write the seam from
// scratch. The naming mirrors the firmware-interface generator so the two files fit together.

import { parseManifest, type Capability, type DeviceIR } from "@chipwright/device-engine";

export interface ScaffoldFile {
  path: string;
  contents: string;
}

export interface ScaffoldResult {
  valid: boolean;
  files: ScaffoldFile[];
}

function upper(value: string): string {
  return value.toUpperCase();
}

// Delegates one generated prototype to the HAL under its capability key. This is the body a
// developer would otherwise write by hand for every capability.
function prototypeImpl(cap: Capability): string {
  if (cap.kind === "sensor") {
    return [
      `oh_status_t oh_${cap.key}_read(float *out_value) {`,
      `  return oh_hal_read_sensor("${cap.key}", out_value);`,
      `}`,
    ].join("\n");
  }
  return [
    `oh_status_t oh_${cap.key}_set_mode(oh_${cap.key}_mode_t mode) {`,
    `  return oh_hal_set_actuator_mode("${cap.key}", (int)mode);`,
    `}`,
  ].join("\n");
}

// A simulated driver so the device builds and streams without hardware attached. The developer
// replaces the marked body with a real read or write for their board; the registration wiring
// stays the same. This mirrors sdk/firmware/bsp/native.
function driverImpl(cap: Capability): string {
  if (cap.kind === "sensor") {
    const unit = cap.unit ?? "unitless";
    return [
      `static oh_status_t ${cap.key}_read_driver(void *ctx, float *out_value) {`,
      `  (void)ctx;`,
      `  static float value = 0.0f;`,
      `  value += 0.1f;`,
      `  *out_value = value;  // Replace with a real sensor read (unit: ${unit}).`,
      `  return OH_OK;`,
      `}`,
    ].join("\n");
  }
  return [
    `static oh_status_t ${cap.key}_set_mode_driver(void *ctx, int mode) {`,
    `  (void)ctx;`,
    `  oh_log(OH_LOG_INFO, "${cap.key} mode -> %d", mode);  // Replace with a real actuator write.`,
    `  return OH_OK;`,
    `}`,
  ].join("\n");
}

function registerCall(cap: Capability): string {
  if (cap.kind === "sensor") {
    const unit = cap.unit ?? "unitless";
    return [
      `  const oh_sensor_driver_t ${cap.key}_driver = {.read = ${cap.key}_read_driver, .ctx = NULL};`,
      `  status = oh_hal_register_sensor("${cap.key}", "${unit}", ${cap.key}_driver);`,
      `  if (status != OH_OK) {`,
      `    return status;`,
      `  }`,
    ].join("\n");
  }
  return [
    `  const oh_actuator_driver_t ${cap.key}_driver = {.set_mode = ${cap.key}_set_mode_driver, .ctx = NULL};`,
    `  status = oh_hal_register_actuator("${cap.key}", ${cap.key}_driver);`,
    `  if (status != OH_OK) {`,
    `    return status;`,
    `  }`,
  ].join("\n");
}

function moduleSource(ir: DeviceIR): string {
  const name = ir.device.name;
  const caps = ir.capabilities;
  const prototypes =
    caps.length > 0 ? caps.map(prototypeImpl).join("\n\n") : "// This device declares no capabilities yet.";
  const drivers = caps.length > 0 ? caps.map(driverImpl).join("\n\n") : "";
  const registrations = caps.map(registerCall).join("\n");
  return [
    `// Starter firmware for ${name}, generated by OpenHome Studio as an editable starting point.`,
    `// It implements the capability prototypes from ${name}_interface.h by delegating to the HAL,`,
    `// registers a driver for each capability, and runs the SDK telemetry loop. Everything above`,
    `// the HAL is the same across chips; replace the simulated drivers below with reads and writes`,
    `// for your board. See firmware/README.md and docs/adding-a-board.md.`,
    ``,
    `#include "openhome/hal.h"`,
    `#include "openhome/sdk.h"`,
    `#include "${name}_interface.h"`,
    ``,
    `// Capability interface: each generated prototype delegates to the HAL under its key, so`,
    `// device logic never names a register.`,
    prototypes,
    ``,
    ...(drivers.length > 0
      ? [
          `// Board drivers: simulated so the device runs with no hardware attached. Replace each`,
          `// marked body with a real read or write for your board.`,
          drivers,
          ``,
        ]
      : []),
    `static oh_status_t register_drivers(void) {`,
    ...(caps.length > 0 ? [`  oh_status_t status;`, registrations] : []),
    `  return OH_OK;`,
    `}`,
    ``,
    `int main(void) {`,
    `  const oh_device_t device = {.name = "${name}"};`,
    `  if (register_drivers() != OH_OK) {`,
    `    return 1;`,
    `  }`,
    `  if (oh_device_init(&device) != OH_OK) {`,
    `    return 1;`,
    `  }`,
    `  oh_device_run(&device, 10);`,
    `  return 0;`,
    `}`,
    ``,
  ].join("\n");
}

function readme(ir: DeviceIR): string {
  const name = ir.device.name;
  return [
    `# ${name} firmware`,
    ``,
    `Starter firmware scaffolded by OpenHome Studio. \`${name}.c\` implements the capability`,
    `prototypes from the generated interface (\`generated/firmware/${name}_interface.h\`) by`,
    `delegating to the OpenHome HAL, and registers a simulated driver for each capability so it`,
    `builds and streams telemetry with no hardware attached.`,
    ``,
    `This file is yours to edit; it is not regenerated. Re-running Generate only rewrites`,
    `\`generated/\`, so your driver code is never overwritten.`,
    ``,
    `## Build and run on the host`,
    ``,
    `Compile against the SDK headers and the generated interface, linking the SDK and a BSP`,
    `(the native BSP shown here builds with no board):`,
    ``,
    "```sh",
    `cc -std=c11 -Wall -Wextra \\`,
    `  -I <openhome>/sdk/firmware/include \\`,
    `  -I generated/firmware \\`,
    `  ${name}.c <openhome>/sdk/firmware/src/*.c \\`,
    `  -o ${name}`,
    `./${name}`,
    "```",
    ``,
    `## Put it on a board`,
    ``,
    `Replace the simulated driver bodies in \`${name}.c\` with real reads and writes for your`,
    `chip, or move them into a board support package. The ESP32-C6 target under`,
    `\`sdk/firmware/targets/esp32c6\` is a worked example, and \`docs/adding-a-board.md\` walks`,
    `through bringing up a new chip.`,
    ``,
  ].join("\n");
}

// Produces the starter firmware files for a manifest, with paths relative to the device
// directory. Returns no files when the manifest does not compile, so the shell can surface the
// diagnostics rather than scaffold against a broken definition.
export function scaffold(manifestYaml: string): ScaffoldResult {
  const { ir } = parseManifest(manifestYaml);
  if (ir === null) {
    return { valid: false, files: [] };
  }
  const name = ir.device.name;
  return {
    valid: true,
    files: [
      { path: `firmware/${name}.c`, contents: moduleSource(ir) },
      { path: `firmware/README.md`, contents: readme(ir) },
    ],
  };
}
